// <auto-generated />
using System;
using Gabi.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Gabi.Postgres.Migrations
{
    [DbContext(typeof(GabiDbContext))]
    [Migration("20260213180000_AddSeedRuns")]
    partial class AddSeedRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model is in snapshot; this migration only adds seed_runs.
        }
    }
}
