// <auto-generated />
using System;
using Gabi.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Gabi.Postgres.Migrations
{
    [DbContext(typeof(GabiDbContext))]
    [Migration("20260214000000_AddDiscoveryRunsAndPhaseTracking")]
    partial class AddDiscoveryRunsAndPhaseTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model is in snapshot.
        }
    }
}
