"""ZIP downloader for DOU publications from in.gov.br.

Downloads monthly ZIP bundles containing XML files for each DOU section.
URL pattern (public Liferay document library):
    https://www.in.gov.br/documents/{GROUP_ID}/{FOLDER_ID}/S{prefix}{MMYYYY}.zip

The FOLDER_ID changes per month and is stored in a registry JSON file
scraped from the catalog page at:
    https://www.in.gov.br/acesso-a-informacao/dados-abertos/base-de-dados?ano=YYYY&mes=MES

Special edition detection:
    GET https://www.in.gov.br/o/tagsRest/tags/getTags?date=YYYY-MM-DD
    Returns JSON flags: {DO1E: bool, DO2E: bool, DO3E: bool, DO1ESP: bool, ...}

Architecture:
    - Public endpoint requires no authentication (Liferay document library)
    - GROUP_ID (49035712) is the static Liferay site ID
    - FOLDER_ID varies by month — loaded from data/dou_catalog_registry.json
    - Registry covers Jan 2002 → Jan 2026 (289 months)
    - 404 for special editions is normal (not published every day)
"""
from __future__ import annotations

import hashlib
import json
import random
import sys
import time
import zipfile
from dataclasses import dataclass, field
from datetime import date, timedelta
from pathlib import Path
from typing import Any

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

from ingest.date_selector import DateRange


# ---------------------------------------------------------------------------
# Constants — Liferay document library coordinates
# ---------------------------------------------------------------------------

GROUP_ID = "49035712"
BASE_DOCUMENT_URL = "https://www.in.gov.br/documents"
TAGS_API_URL = "https://www.in.gov.br/o/tagsRest/tags/getTags"

# Default registry path (relative to project root)
_DEFAULT_REGISTRY_PATH = Path("data/dou_catalog_registry.json")

# Section code → ZIP filename prefix on server
# URL pattern: S{prefix}{MMYYYY}.zip  where MM=month, YYYY=year
# Confirmed: S01012026.zip = Section 1, January 2026
SECTIONS: dict[str, str] = {
    "do1":  "S01",
    "do2":  "S02",
    "do3":  "S03",
}

# Extra edition ZIP prefix — needs validation against server
# Tentative patterns based on tags API flags: DO1E, DO2E, DO3E
EXTRA_SECTIONS: dict[str, str] = {
    "do1e": "S01E",
    "do2e": "S02E",
    "do3e": "S03E",
}

ALL_SECTIONS: dict[str, str] = {**SECTIONS, **EXTRA_SECTIONS}

# Tags API flag → section code mapping
TAGS_SECTION_MAP: dict[str, str] = {
    "DO1E":   "do1e",
    "DO2E":   "do2e",
    "DO3E":   "do3e",
    "DO1ESP": "do1esp",
    "DO2ESP": "do2esp",
    "DO1A":   "do1a",
}

# ---------------------------------------------------------------------------
# FolderId registry — maps YYYY-MM → Liferay folderId
# File registry — maps YYYY-MM → list[str] of actual ZIP filenames on server
# ---------------------------------------------------------------------------

_FOLDER_REGISTRY: dict[str, int] = {}   # loaded lazily
_FILE_REGISTRY: dict[str, list[str]] = {}  # loaded lazily


def load_folder_registry(path: Path | None = None) -> dict[str, int]:
    """Load the month→folderId and month→files registries from JSON.

    The registry is generated by `python -m ingest.catalog_scraper`.
    Falls back to the default path if not specified.
    """
    global _FOLDER_REGISTRY, _FILE_REGISTRY
    if _FOLDER_REGISTRY:
        return _FOLDER_REGISTRY

    if path is None:
        # Try relative to CWD first, then relative to this file's parent
        for candidate in [
            _DEFAULT_REGISTRY_PATH,
            Path(__file__).resolve().parent.parent / "data" / "dou_catalog_registry.json",
        ]:
            if candidate.exists():
                path = candidate
                break

    if path is None or not path.exists():
        _log(f"registry: not found at {path or _DEFAULT_REGISTRY_PATH}")
        return {}

    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        _FOLDER_REGISTRY = {k: int(v) for k, v in data.get("folder_ids", {}).items()}
        _FILE_REGISTRY = {k: v for k, v in data.get("files", {}).items()}
        _log(f"registry: loaded {len(_FOLDER_REGISTRY)} months from {path}")
    except Exception as ex:
        _log(f"registry: error loading {path}: {ex}")

    return _FOLDER_REGISTRY


def get_folder_id(pub_date: date) -> int | None:
    """Look up the folderId for a given month.

    Returns None if the month is not in the registry.
    """
    registry = load_folder_registry()
    month_key = pub_date.strftime("%Y-%m")
    return registry.get(month_key)


# Rotating User-Agent pool to avoid CDN fingerprinting
_USER_AGENTS: list[str] = [
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 Edg/145.0.0.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0",
]

DEFAULT_TIMEOUT = 60
DEFAULT_RETRY_ATTEMPTS = 3
MIN_REQUEST_DELAY = 0.5  # seconds between requests


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class ZIPTarget:
    """A single ZIP to download."""
    section: str          # do1, do2, do3, do1e, do2e, do3e
    pub_date: date        # For monthly: 1st of month. For daily: exact date.
    url: str
    filename: str         # server filename (e.g. S01012026.zip)
    local_filename: str   # local filename (e.g. 2026-01_DO1.zip)

    @property
    def date_str(self) -> str:
        return self.pub_date.strftime("%m%Y")


@dataclass(slots=True)
class DownloadResult:
    """Result of a single ZIP download."""
    target: ZIPTarget
    success: bool
    local_path: Path | None = None
    size_bytes: int = 0
    sha256: str | None = None
    download_time_ms: int = 0
    error: str | None = None
    http_status: int | None = None


@dataclass(slots=True)
class DownloadManifest:
    """Tracks a batch of downloads."""
    targets: list[ZIPTarget] = field(default_factory=list)
    results: list[DownloadResult] = field(default_factory=list)

    @property
    def downloaded(self) -> list[DownloadResult]:
        return [r for r in self.results if r.success]

    @property
    def failed(self) -> list[DownloadResult]:
        return [r for r in self.results if not r.success]

    @property
    def total_bytes(self) -> int:
        return sum(r.size_bytes for r in self.results if r.success)


@dataclass(slots=True)
class ExtractionResult:
    """Result of extracting XML files from a ZIP."""
    zip_path: Path
    xml_files: list[Path]
    image_files: list[Path]
    errors: list[str]


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

def _log(msg: str) -> None:
    print(msg, file=sys.stderr, flush=True)


# ---------------------------------------------------------------------------
# HTTP session factory
# ---------------------------------------------------------------------------

def _build_session(max_retries: int = DEFAULT_RETRY_ATTEMPTS) -> requests.Session:
    """Build a requests session with retry + backoff."""
    session = requests.Session()
    retry = Retry(
        total=max_retries,
        backoff_factor=1.0,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"],
    )
    adapter = HTTPAdapter(max_retries=retry, pool_connections=5, pool_maxsize=5)
    session.mount("https://", adapter)
    session.mount("http://", adapter)
    session.headers.update({
        "Accept": "application/octet-stream, application/zip, */*",
        "Accept-Language": "pt-BR,pt;q=0.9,en;q=0.8",
        "Accept-Encoding": "gzip, deflate, br",
        "DNT": "1",
        "Connection": "keep-alive",
    })
    return session


def _random_ua() -> str:
    return random.choice(_USER_AGENTS)


# ---------------------------------------------------------------------------
# Tags API — special edition detection
# ---------------------------------------------------------------------------

def detect_special_editions(
    pub_date: date,
    session: requests.Session | None = None,
    timeout: int = DEFAULT_TIMEOUT,
) -> dict[str, bool]:
    """Query Liferay tags API for special edition flags on a given date.

    Returns:
        Dict mapping tag names to booleans, e.g. {"DO1E": True, "DO2E": False, ...}
        Returns empty dict on failure.
    """
    own_session = session is None
    if own_session:
        session = _build_session()
    try:
        resp = session.get(
            TAGS_API_URL,
            params={"date": pub_date.isoformat()},
            headers={"User-Agent": _random_ua(), "X-Requested-With": "XMLHttpRequest"},
            timeout=timeout,
        )
        if resp.status_code != 200:
            _log(f"tags_api: HTTP {resp.status_code} for {pub_date.isoformat()}")
            return {}
        data = resp.json()
        # Liferay wraps in {"javaClass": ..., "serializable": {"jsonObject": {<flags>}}}
        if isinstance(data, dict):
            if "serializable" in data:
                flags = data["serializable"].get("jsonObject", {})
            elif "jsonObject" in data:
                flags = data["jsonObject"]
            else:
                flags = data
            return {k: bool(v) for k, v in flags.items()}
        return {}
    except Exception as ex:
        _log(f"tags_api: error for {pub_date.isoformat()}: {ex}")
        return {}
    finally:
        if own_session and session:
            session.close()


# ---------------------------------------------------------------------------
# URL generation
# ---------------------------------------------------------------------------

def _section_to_local(section: str) -> str:
    """Convert section code to local filename segment (e.g. do1 → DO1, do1e → DO1E)."""
    return section.upper()


def build_zip_url(section: str, pub_date: date) -> ZIPTarget | None:
    """Build the monthly archive ZIP download URL for a section and month.

    The public endpoint hosts monthly archives:
      https://www.in.gov.br/documents/{GROUP_ID}/{FOLDER_ID}/S{prefix}{MM}{YYYY}.zip
    e.g. S01012026.zip = Section 1, January 2026

    The FOLDER_ID is looked up from the catalog registry (per-month).

    Args:
        section: Section code (do1, do2, do3, do1e, do2e, do3e)
        pub_date: Any date in the target month (day is ignored)

    Returns:
        ZIPTarget with URL and filenames, or None if folderId not found.
    """
    prefix = ALL_SECTIONS.get(section)
    if prefix is None:
        raise ValueError(f"Unknown section: {section}. Expected one of {list(ALL_SECTIONS)}")

    # Normalize to 1st of month
    month_date = pub_date.replace(day=1)

    # Look up folderId from registry
    folder_id = get_folder_id(month_date)
    if folder_id is None:
        _log(f"build_url: no folderId for {month_date.strftime('%Y-%m')} — skipping {section}")
        return None

    # Monthly archive: MMYYYY
    month_str = pub_date.strftime("%m%Y")
    server_filename = f"{prefix}{month_str}.zip"
    # Local name: YYYY-MM_SECTION.zip (e.g. 2026-01_DO1.zip)
    local_filename = f"{pub_date.strftime('%Y-%m')}_{_section_to_local(section)}.zip"
    url = f"{BASE_DOCUMENT_URL}/{GROUP_ID}/{folder_id}/{server_filename}"

    return ZIPTarget(
        section=section,
        pub_date=month_date,
        url=url,
        filename=server_filename,
        local_filename=local_filename,
    )


def _filename_to_section(fname: str) -> str | None:
    """Infer section code from a registry filename.

    Maps e.g. 'S01012026.zip' → 'do1', 'S03E122025.zip' → 'do3e',
    'S01122025_Parte1.zip' → 'do1'.
    Returns None if the filename doesn't match any known pattern.
    """
    base = fname.split("_")[0]  # strip _Parte suffixes
    base = base.replace(".zip", "")

    # Reverse-lookup: prefix → section
    for section, prefix in ALL_SECTIONS.items():
        # base should start with prefix followed by MMYYYY digits
        if base.startswith(prefix) and len(base) == len(prefix) + 6:
            return section
    return None


def _registry_targets_for_month(
    month_key: str,
    target_sections: list[str],
) -> list[ZIPTarget]:
    """Build ZIPTargets from the registry file list for a given month.

    Handles split files (e.g. S01122025_Parte1.zip) by generating one target
    per physical file, all sharing the same section code.
    """
    folder_id = _FOLDER_REGISTRY.get(month_key)
    if folder_id is None:
        return []

    reg_files = _FILE_REGISTRY.get(month_key, [])
    year = int(month_key[:4])
    month = int(month_key[5:7])
    month_date = date(year, month, 1)

    targets: list[ZIPTarget] = []
    for fname in reg_files:
        section = _filename_to_section(fname)
        if section is None or section not in target_sections:
            continue
        url = f"{BASE_DOCUMENT_URL}/{GROUP_ID}/{folder_id}/{fname}"
        # Local name preserves original filename for split parts
        local_filename = f"{month_key}_{section.upper()}_{fname}" if "_Parte" in fname else (
            f"{month_key}_{section.upper()}.zip"
        )
        targets.append(ZIPTarget(
            section=section,
            pub_date=month_date,
            url=url,
            filename=fname,
            local_filename=local_filename,
        ))
    return targets


def build_targets(
    date_range: DateRange,
    sections: list[str] | None = None,
    include_extras: bool = True,
    session: requests.Session | None = None,
) -> list[ZIPTarget]:
    """Generate monthly archive download targets for a date range.

    Uses the catalog registry file list when available, which correctly handles
    split files (_Parte1, _Parte2, etc.) and months with missing sections.
    Falls back to constructed URLs for months not in the file registry.

    Deduplicates by month — each unique month appears only once.

    Args:
        date_range: Start/end dates (months covered by this range are targeted)
        sections: Override sections (default: regular DO1/DO2/DO3)
        include_extras: Whether to also target extra editions

    Returns:
        List of ZIPTarget objects (one per section per month)
    """
    target_sections = sections if sections is not None else list(SECTIONS)
    if include_extras and sections is None:
        target_sections = list(ALL_SECTIONS)

    # Ensure registry is loaded
    load_folder_registry()

    # Discover unique months in the range
    seen_months: set[str] = set()
    targets: list[ZIPTarget] = []
    skipped = 0

    for d in date_range.dates():
        month_key = d.strftime("%Y-%m")
        if month_key in seen_months:
            continue
        seen_months.add(month_key)

        # Use registry file list (handles _Parte splits)
        reg_files = _FILE_REGISTRY.get(month_key)
        if reg_files:
            month_targets = _registry_targets_for_month(month_key, target_sections)
            targets.extend(month_targets)
            if not month_targets:
                skipped += 1
        else:
            # Fallback: construct URL from section+date (for months not in file registry)
            for section in target_sections:
                target = build_zip_url(section, d)
                if target is not None:
                    targets.append(target)
                else:
                    skipped += 1

    if skipped:
        _log(f"build_targets: {skipped} targets skipped (no folderId or no matching files)")

    return targets


# ---------------------------------------------------------------------------
# Download
# ---------------------------------------------------------------------------

def download_zip(
    target: ZIPTarget,
    output_dir: Path,
    session: requests.Session | None = None,
    timeout: int = DEFAULT_TIMEOUT,
    skip_existing: bool = True,
) -> DownloadResult:
    """Download a single ZIP file.

    Args:
        target: Download target
        output_dir: Directory to save the file
        session: Reusable requests session
        timeout: HTTP timeout in seconds
        skip_existing: Skip if local file already exists with non-zero size

    Returns:
        DownloadResult with success/failure info
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    local_path = output_dir / target.local_filename

    # Skip if already downloaded
    if skip_existing and local_path.exists() and local_path.stat().st_size > 0:
        sha = file_sha256(local_path)
        return DownloadResult(
            target=target,
            success=True,
            local_path=local_path,
            size_bytes=local_path.stat().st_size,
            sha256=sha,
            download_time_ms=0,
            error=None,
            http_status=None,
        )

    own_session = session is None
    if own_session:
        session = _build_session()

    start_ms = time.monotonic()
    try:
        resp = session.get(
            target.url,
            headers={"User-Agent": _random_ua()},
            timeout=timeout,
            stream=True,
        )

        if resp.status_code == 404:
            # Normal for extra editions that don't exist on this date
            return DownloadResult(
                target=target,
                success=False,
                error="HTTP 404",
                http_status=404,
            )

        resp.raise_for_status()

        # Stream to file
        h = hashlib.sha256()
        size = 0
        with open(local_path, "wb") as f:
            for chunk in resp.iter_content(chunk_size=65536):
                f.write(chunk)
                h.update(chunk)
                size += len(chunk)

        elapsed_ms = int((time.monotonic() - start_ms) * 1000)
        sha = h.hexdigest()

        _log(
            f"download: {target.local_filename} "
            f"size={size:,} sha256={sha[:16]}... "
            f"time={elapsed_ms}ms"
        )

        return DownloadResult(
            target=target,
            success=True,
            local_path=local_path,
            size_bytes=size,
            sha256=sha,
            download_time_ms=elapsed_ms,
        )

    except requests.HTTPError as ex:
        status = ex.response.status_code if ex.response is not None else None
        return DownloadResult(
            target=target,
            success=False,
            error=f"HTTP {status}",
            http_status=status,
        )
    except Exception as ex:
        return DownloadResult(
            target=target,
            success=False,
            error=str(ex),
        )
    finally:
        if own_session and session:
            session.close()


def download_batch(
    targets: list[ZIPTarget],
    output_dir: Path,
    delay: float = MIN_REQUEST_DELAY,
    skip_existing: bool = True,
) -> DownloadManifest:
    """Download a batch of ZIP files sequentially with rate limiting.

    Args:
        targets: List of download targets
        output_dir: Directory to save files
        delay: Minimum delay between requests (seconds)
        skip_existing: Skip files already on disk

    Returns:
        DownloadManifest with all results
    """
    manifest = DownloadManifest(targets=targets)
    session = _build_session()

    try:
        for idx, target in enumerate(targets, start=1):
            result = download_zip(
                target, output_dir, session=session, skip_existing=skip_existing
            )
            manifest.results.append(result)

            status = "OK" if result.success else result.error
            _log(
                f"batch [{idx}/{len(targets)}]: "
                f"{target.local_filename} → {status}"
            )

            # Rate-limit (skip delay for cached/skipped files)
            if result.download_time_ms > 0 and idx < len(targets):
                time.sleep(delay + random.uniform(0, 0.3))
    finally:
        session.close()

    _log(
        f"batch done: {len(manifest.downloaded)}/{len(targets)} ok, "
        f"{len(manifest.failed)} failed, "
        f"{manifest.total_bytes:,} bytes"
    )
    return manifest


# ---------------------------------------------------------------------------
# ZIP extraction
# ---------------------------------------------------------------------------

_XML_EXTENSIONS = frozenset({".xml"})
_IMAGE_EXTENSIONS = frozenset({".png", ".jpg", ".jpeg", ".gif", ".bmp", ".tiff"})


def extract_xml_from_zip(
    zip_path: Path,
    output_dir: Path | None = None,
) -> ExtractionResult:
    """Extract XML files from a DOU ZIP bundle.

    Args:
        zip_path: Path to the ZIP file
        output_dir: Directory to extract to (default: zip_path.parent / zip_path.stem)

    Returns:
        ExtractionResult with paths to extracted XML and image files
    """
    if output_dir is None:
        output_dir = zip_path.parent / zip_path.stem

    output_dir.mkdir(parents=True, exist_ok=True)
    xml_files: list[Path] = []
    image_files: list[Path] = []
    errors: list[str] = []

    try:
        with zipfile.ZipFile(zip_path, "r") as zf:
            for info in zf.infolist():
                if info.is_dir():
                    continue

                name = info.filename
                suffix = Path(name).suffix.lower()

                if suffix in _XML_EXTENSIONS:
                    target_path = output_dir / Path(name).name
                    try:
                        with zf.open(info) as src, open(target_path, "wb") as dst:
                            dst.write(src.read())
                        xml_files.append(target_path)
                    except Exception as ex:
                        errors.append(f"extract {name}: {ex}")

                elif suffix in _IMAGE_EXTENSIONS:
                    target_path = output_dir / Path(name).name
                    try:
                        with zf.open(info) as src, open(target_path, "wb") as dst:
                            dst.write(src.read())
                        image_files.append(target_path)
                    except Exception as ex:
                        errors.append(f"extract {name}: {ex}")

    except zipfile.BadZipFile as ex:
        errors.append(f"bad zip: {ex}")
    except Exception as ex:
        errors.append(f"open zip: {ex}")

    return ExtractionResult(
        zip_path=zip_path,
        xml_files=sorted(xml_files),
        image_files=sorted(image_files),
        errors=errors,
    )


# ---------------------------------------------------------------------------
# Manifest I/O
# ---------------------------------------------------------------------------

def write_manifest(manifest: DownloadManifest, outdir: Path) -> Path:
    """Write download manifest to JSON file."""
    outdir.mkdir(parents=True, exist_ok=True)
    manifest_path = outdir / "manifest.json"

    dates_seen: set[str] = set()
    sections_seen: set[str] = set()
    files: list[dict[str, Any]] = []

    for r in manifest.results:
        t = r.target
        dates_seen.add(t.pub_date.isoformat())
        sections_seen.add(_section_to_local(t.section))
        files.append({
            "date": t.pub_date.isoformat(),
            "section": _section_to_local(t.section),
            "success": r.success,
            "filename": t.local_filename,
            "size_bytes": r.size_bytes,
            "sha256": r.sha256,
            "download_time_ms": r.download_time_ms,
            "error": r.error,
        })

    data = {
        "dates": sorted(dates_seen, reverse=True),
        "sections": sorted(sections_seen),
        "total_files": len(manifest.results),
        "successful": len(manifest.downloaded),
        "failed": len(manifest.failed),
        "total_bytes": manifest.total_bytes,
        "files": files,
    }

    manifest_path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    return manifest_path


def file_sha256(filepath: Path) -> str:
    """Compute SHA-256 hex digest of a file."""
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()
