import {
  Search,
  FileText,
  Home,
  ArrowLeft,
  Filter,
  X,
  ChevronRight,
  ChevronDown,
  Calendar,
  ExternalLink,
  Image,
  Share2,
  BookOpen,
  TrendingUp,
  Clock,
  Hash,
  Building,
  GitBranch,
  Command,
  BarChart3,
  Settings,
  Download,
  Star,
  Lock,
  MessageSquare,
  Copy,
} from 'lucide-react';

export const Icons = {
  search: Search,
  document: FileText,
  home: Home,
  back: ArrowLeft,
  filter: Filter,
  close: X,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  calendar: Calendar,
  externalLink: ExternalLink,
  image: Image,
  share: Share2,
  book: BookOpen,
  trending: TrendingUp,
  clock: Clock,
  hash: Hash,
  building: Building,
  gitBranch: GitBranch,
  command: Command,
  analytics: BarChart3,
  settings: Settings,
  download: Download,
  star: Star,
  lock: Lock,
  chat: MessageSquare,
  copy: Copy,
};
