server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index /dist/index.html;

    location /dist/assets/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /dist/ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=300";
    }

    location / {
        try_files $uri /dist/index.html;
        add_header Cache-Control "no-store";
    }
}
